# Generated by Django 4.0.1 on 2022-02-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klient',
            fields=[
                ('Nazwa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NIP', models.CharField(max_length=13)),
                ('Ulica', models.CharField(max_length=100)),
                ('Adres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pozycjafaktury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.TextField()),
                ('Jednostka', models.CharField(default='Szt.', max_length=5)),
                ('Ilosc', models.FloatField(default=1)),
                ('Cena_Netto', models.FloatField()),
                ('Podatek', models.IntegerField(default=23)),
            ],
        ),
        migrations.CreateModel(
            name='faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_faktury', models.CharField(max_length=90)),
                ('Numer_faktury', models.CharField(max_length=90)),
                ('Data_sprzedaży', models.DateField()),
                ('Data_wystawienia', models.DateField()),
                ('Termin_płatności', models.DateField()),
                ('Zapłacono', models.FloatField(default=0)),
                ('Termin_płatności_dni', models.PositiveIntegerField(default=1)),
                ('firma_klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svg2pdf.klient')),
                ('pozycje', models.ManyToManyField(to='svg2pdf.pozycjafaktury')),
            ],
        ),
    ]
