# Generated by Django 4.0.1 on 2022-02-10 12:47

from django.db import migrations, models
import django.db.models.deletion
import svg2pdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('nazwa', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=13)),
                ('ulica', models.CharField(max_length=45)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JednostkaM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Szt', max_length=8)),
                ('dziesietna', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SposobPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Przelew na konto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pozycjafaktury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
                ('ilosc', models.FloatField(default=1, validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_zero])),
                ('cena_Netto', models.FloatField(validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_num, svg2pdf.models.validate_zero])),
                ('podatek', models.IntegerField(default=23, validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_zero])),
                ('jednostka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svg2pdf.jednostkam')),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_faktury', models.CharField(max_length=8)),
                ('numer_faktury', models.CharField(max_length=15)),
                ('data_sprzedazy', models.DateField()),
                ('data_wystawienia', models.DateField()),
                ('termin_platnosci', models.DateField()),
                ('zaplacono', models.FloatField(default=0, validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_num])),
                ('termin_platnosci_dni', models.PositiveIntegerField(default=1)),
                ('firma_klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nabywca', to='svg2pdf.firma')),
                ('firma_sprzedawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprzedawca', to='svg2pdf.firma')),
                ('pozycje', models.ManyToManyField(to='svg2pdf.Pozycjafaktury')),
                ('sposob_platnosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svg2pdf.sposobplat')),
            ],
        ),
    ]
