# Generated by Django 4.0.2 on 2022-02-09 09:40

from django.db import migrations, models
import svg2pdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('svg2pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='Zapłacono',
            field=models.FloatField(default=0, validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_num]),
        ),
        migrations.AlterField(
            model_name='pozycjafaktury',
            name='Cena_Netto',
            field=models.FloatField(validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_num, svg2pdf.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='pozycjafaktury',
            name='Ilosc',
            field=models.FloatField(default=1, validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_zero]),
        ),
        migrations.AlterField(
            model_name='pozycjafaktury',
            name='Podatek',
            field=models.IntegerField(default=23, validators=[svg2pdf.models.validate_neg, svg2pdf.models.validate_zero]),
        ),
    ]
