# Generated by Django 4.0.1 on 2022-02-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svg2pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SposobPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Przelew na konto', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='faktura',
            name='nazwa_faktury',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='numer_faktury',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='firma',
            name='adres',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='firma',
            name='nazwa',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firma',
            name='ulica',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='jednostkam',
            name='nazwa',
            field=models.CharField(default='Szt', max_length=8),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='sposob_platnosci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svg2pdf.sposobplat'),
        ),
    ]
